---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami
  url: https://charts.bitnami.com/bitnami
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: traefik
  url: https://traefik.github.io/charts
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: mayastor
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: mayastor
  url: https://openebs.github.io/mayastor-extensions
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: hashicorp
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: hashicorp
  url: https://helm.releases.hashicorp.com
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: rimusz
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: rimusz
  url: https://charts.rimusz.net
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-pfsense-controller
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: kubernetes-pfsense-controller
  url: https://travisghansen.github.io/kubernetes-pfsense-controller-chart/
  type: helm
